### ISSUE TITLE
Hópavinna eða ekki.

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#1]
> Verkefnin **á að** vinna í pörum, **ef** tveir vinna saman viljum við sjá jafnt framlag frá báðum aðilum inn á Git history,

Sem sagt spurninginn mín eru tvær: 

1. Verður maður að vinna í pörum eða má vinna einn?
2. Ef svo, Þarf maður að finna sjálfur mannesku til að vinna með eða er sett mann í hóp handahófskennt.

**Comment by hap2000** [comment]
1. Það er hægt að óska eftir að vinna verkefnið einn. 
2. Þið megið velja ykkur félaga.

**Comment by eythoro16** [comment]
Takk, á að senda email til þín ef maður vill óskast eftir því að vinna einn?
Mæliru á móti því að vinna einn? Langa að vita hver er svona aðal hugsuninn um að láta okkur vinna í pörum. Og af hverju er að vera að nota github issues í staðin fyrir piazza?

**Comment by hap2000** [comment]
Nei þarft ekki að senda email. 
Þegar við kenndum þennan áfanga fyrst höfum við þetta sem einstaklingsverkefni, þannig að það er vel hægt að vinna þetta einn en það getur líka verið gott að vinna þetta með félaga. Það er mjög algeng leið í dag að vinna saman í pörum, gott tækifæri til að prófa það. Það hentar vel í þessu verkefni, það er talsvert um rannsóknarvinnu og það er einmitt kjörið að vinna það saman. 
Áfanginn fer meira og minn fram á GitHub og þess vegna ákváðum við að notast frekar við GitHub issues. Líka fín leið til að kynnast því. Við hittumst daglega og því ekki eins mikil þörf á spjalli, við sjáum þetta fyrst og fremst til að senda inn ef þið eruð í vandræðum með einhverja hluti í verkefninu, GitHub issues henta að mörgu leiti betur í það, er í grunninn hugsað til að setja fram spurningar um efni tengt kóða.
