### ISSUE TITLE
deploy.sh - Create a new instance using Terraform.

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#10]
Er að meina bara terraform init, plan og apply?
eða þarf að búa til infrastructure.tf first með kóðanum sem var gefinn okkur? og svo calla terraform init, plan og apply?

**Comment by eythoro16** [comment]
þarf kanski ekki að gera það þar sem infrastructure fylgir githubinu

**Comment by IronPeak** [comment]
scriptið ætti ekki að búa til .tf fileinn, hann á að vera til í repository-inu.

**Comment by eythoro16** [comment]
takk, var aðeins ruglaður í gær um hvernig þetta gekk allt sama. Fann útur því í dag.
