### ISSUE TITLE
No space left on Jenkins

### ISSUE THREAD

**Issue by skulia15** [hgop/syllabus-2018#101]
Ég næ ekki að klára build afþví að Jenkins er ekki með neitt pláss eftir. Hef reynt að eyða previous builds en ég næ ekki að skapa nóg pláss. Er einhver leið til að stækka minnið á Jenkins vélinni?

![image](https://user-images.githubusercontent.com/16030738/49892494-04b37800-fe41-11e8-9364-9a1407771cdd.png)

![image](https://user-images.githubusercontent.com/16030738/49892527-1ac13880-fe41-11e8-84a9-ac7463365e4a.png)

**Comment by IvarKristinn** [comment]
Gætir þurft að eyða docker images

**Comment by skulia15** [comment]
https://www.totallymoney.com/blog/cleaning-up-docker-images-on-jenkins-build-machines/
Þetta virkaði fyrir mig
