### ISSUE TITLE
How to use hot-shots

### ISSUE THREAD

**Issue by hedinnh** [hgop/syllabus-2018#102]
Er ég að nota þetta rétt? er ekki alveg að skilja hvernig ég nota hot-shots.

ég setti í server.js eftirfarandi:
`const DogStatsD = require('hot-shots');`

`    const statsd = new DogStatsD({
        host: 'my_datadog_container',
        post: '8125',
        errorHandler: function(error) {
            console.log(
                JSON.stringify({
                    log_level: 'error',
                    error: error,
                })
            );
        },
    });`

svo er ég að reyna að gera 

`statsd.increment('page_request');`

þegar ég ræsi dockerana fæ ég reyndar alskonar villur

my_datadog_container_1_d8a2d11bd4c7 | [ AGENT ] 2018-12-12 19:40:36 UTC | ERROR | (docker_main.go:117in fetchForDockerID) | Failed to inspect container e41b80807a70f0052ed8ea16138d511e45be559cdd00eb055c5e1caa0accfb76 - Error: No such container: e41b80807a70f0052ed8ea16138d511e45be559cdd00eb055c5e1caa0accfb76
my_datadog_container_1_d8a2d11bd4c7 | [ AGENT ] 2018-12-12 19:40:36 UTC | WARN | (tagger.go:252 in Tag) | error collecting from docker: Error: No such container: e41b80807a70f0052ed8ea16138d511e45be559cdd00eb055c5e1caa0accfb76

Er einhver með hints? eða er maður að nota þetta rangt?

**Comment by IronPeak** [comment]
myndi sleppa því að taka fram port, er þetta allt outputið úr datadog containernum?

**Comment by hedinnh** [comment]
Hér er pastebin með output frá datadog container.

neðst í því paste er console.log af statsd ojbectinu sem ég er að búa til í kóðanum.

https://pastebin.com/W3a5YqKz

**Comment by hedinnh** [comment]
Já reyndi án þess að setja port. Er ég að gera þetta rétt? eins og ég var að sýna hér fyrir ofan?

**Comment by hedinnh** [comment]
Já ég prufaði að bíða líka og fékk svona payload sent. svo skoða ég inná datadog og þá er ekkert event sem heitir það sem ég er að reyna að senda. er ég að gera þetta rétt í kóðanum sem ég setti inn hér efst í þessu issue?

**Comment by kthorri** [comment]
Increment kemur ekki inn sem event, þegar þú býrð til nýtt dashboard, þá ætti þetta að koma upp sem metric í einhverjum af dálkunum hjá þer. Ef þetta er rétt uppsett.

Reopen ef það er ekki sem skildi.
