### ISSUE TITLE
Connect UI: "create a new git repository"

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#103]
> mkdir game-client
> cd game-client
> git init
> git pull git@github.com:hgop/lucky-21-frontend.git
> rm -rf .git
> cd ..
> git rm --cached game-client

Hvort á að runna þetta bara beint í rootinu eða á að búa til sitt eigin repository inn í rootinu og run-a þessi commands í nýja repository-inu?

ég prófaði fyrstu aðferðina.
```
eybbus@eybbus-VirtualBox:~/code/HGOP$ mkdir game-client
eybbus@eybbus-VirtualBox:~/code/HGOP$ cd game-client/
eybbus@eybbus-VirtualBox:~/code/HGOP/game-client$ git init
Initialized empty Git repository in /home/eybbus/code/HGOP/game-client/.git/
eybbus@eybbus-VirtualBox:~/code/HGOP/game-client$ git pull git@github.com:hgop/lucky-21-frontend.git
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 99 (delta 54), reused 95 (delta 51), pack-reused 0
Unpacking objects: 100% (99/99), done.
From github.com:hgop/lucky-21-frontend
 * branch            HEAD       -> FETCH_HEAD
eybbus@eybbus-VirtualBox:~/code/HGOP/game-client$ rm -rf .git
eybbus@eybbus-VirtualBox:~/code/HGOP/game-client$ cd ..
eybbus@eybbus-VirtualBox:~/code/HGOP$ git rm --cached game-client
fatal: pathspec 'game-client' did not match any files
```
vantar ekki -r í síðasta command-ið?
PS: það vantar í enda dag 12 og 13 hvernig folder layoutið ætti að vera

**Comment by IronPeak** [comment]
ef þú getur pushað folderinnu inn þá ætti þetta að vera í lagi

**Comment by eythoro16** [comment]
á ég ekki annars að
```
 cd game-client
docker build -t gameclient .
```

**Comment by eythoro16** [comment]
það á að push þetta á nytt dockerhub right?
maður er búinn að vera að gera `eythoro16:hgop:<commit>` eða `eythoro16:hgop:test`

með þenna nyjan dockerfile þá pusha-r maður þetta á (miðað við fyrir ofan)
`eythoro16:gameclient:latest`
right?

**Comment by eythoro16** [comment]
eða á ég að halda áfram að nota eythoro16:hgop:<tag>
og tag-a þetta sem gameclient

**Comment by IronPeak** [comment]
gott að búa til nýtt repo a dockerhub

**Comment by kthorri** [comment]
Clientinn og serverinn ætti að vera sitthvort repoið

```
user/server-repo:tag
user/client-repo:tag
```
