### ISSUE TITLE
Jenkins meme

### ISSUE THREAD

**Issue by vidir17** [hgop/syllabus-2018#105]
Jenkins... Alltaf með vesen...
![terraformdestroy](https://user-images.githubusercontent.com/34030379/49898563-44825b80-fe51-11e8-870e-399975326b3a.png)

**Comment by stefaj9** [comment]
![godur](https://user-images.githubusercontent.com/16031820/49901519-4c45fe00-fe59-11e8-91bf-9d9265b292b8.jpg)
