### ISSUE TITLE
Can't access Exam module

### ISSUE THREAD

**Issue by devalberg** [hgop/syllabus-2018#106]
Needs to be opened!

<img width="548" alt="screenshot 2018-12-12 at 21 58 57" src="https://user-images.githubusercontent.com/26262489/49901554-64b61880-fe59-11e8-9aa4-f3ab5ffbe0c9.png">

**Comment by Meggyblond** [comment]
jaaá gaur ertu búinn að update-a credentials?

**Comment by hap2000** [comment]
Komið í lag.
