### ISSUE TITLE
Ekkert sýnispróf undir modules

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#111]
Hæ, kennari setti inn tilkynningu seint í gærkvöldi með link um að væri komið sýnispróf undir Modules. En það er ekkert sýnispróf og linkurinn virkar ekki. Væri æðislegt ef hægt væri að laga þetta sem allra fyrst.

**Comment by eddast** [comment]
Sorry !!! Skoðaði issues ekki nógu vel þannig þetta issue er duplicate af @106 - engu að síður valid

**Comment by hap2000** [comment]
Ætti að vera komið í lag núna.
Smá Canvas vankunnátta, yfirflokkurinn var ekki "Published"
