### ISSUE TITLE
Source control vs version control vs revision control

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#112]
Hæ,

Það kom á prófinu 2015 þessi spurning "What is the difference between version control systems, revision control systems and source control systems?". Í áfanganum virðist enginn munur á þessum conceptum m.v. hvað stendur á þessarri glæru:

![image](https://user-images.githubusercontent.com/16048954/49928134-657d9780-feb7-11e8-94f8-3005d9a0960a.png)

en almennt er gerður greinamunur á þessu, https://www.quora.com/What-is-the-difference-between-version-control-and-source-control

Hvort er rétt???

**Comment by IronPeak** [comment]
Eins og ég skil þetta þá eru Source og Revision CS subset af Version CS
Forwardaði þessu á Hannes og Gulla þeir leiðrétta mig ef þetta er vitlaust hjá mér.

**Comment by hap2000** [comment]
Það er engin munur á þessu. Þetta er svo kölluð "Trick question". Við stefnum ekki á að vera með neinar svoleiðis spurningar í ár :)

**Comment by eddast** [comment]
Samt mjög villandi trick question! En mér lýst hins vegar rosalega vel á hjá ykkur að sleppa þeim á morgun hehe :)
