### ISSUE TITLE
Virtual machine crashed and wont start

### ISSUE THREAD

**Issue by Kristoferu16** [hgop/syllabus-2018#113]
![image](https://user-images.githubusercontent.com/24221678/49939200-0e39f000-fed4-11e8-950b-9d0e66ebe3c0.png)
Er ekki alveg að vita hvernig ég á að snúa mér í þessu og hef eiginlega ekki tíma til að skoða þetta í dag útaf prófinu. Hún gaf mér warning í gær að ég væri með low disk space eftir þannig að henti fullt af drasli út til að losa pláss og nú í morgun vill hún ekki starta.

**Comment by Kristoferu16** [comment]
Var buinn að restarta henni nokkrum sinnum í gær þannig að vesenið ætti ekki að vera eitthvað sem ég henti út

**Comment by IvarKristinn** [comment]
Sælir og massaður, var lenti í því í viku 1 að fá bara ekkert UI, en ég ákvað þá bara að setja upp nýja með meira HD/RAM

**Comment by Kristoferu16** [comment]
Væri alveg til í það bara held að það fari of mikill tími í það að setja allt upp aftur

**Comment by IronPeak** [comment]
Installaðiru datadog agent á þína eigin tölvu?

**Comment by Kristoferu16** [comment]
nei á virtual vélina

**Comment by IronPeak** [comment]
Já, en installaðiru datadog agentinum sem service á development vélinni?

**Comment by Kristoferu16** [comment]
nei fyrirgefðu installaði honum ekki gerði bara account og keyyrði docker compose með data dog kóðanum sem bjó til container og gerði síðan monitor fyrir cpu í web clientinum

**Comment by IronPeak** [comment]
Hvað er screenshottið þá að sýna?

**Comment by Kristoferu16** [comment]
Þetta er það sem ég fæ upp þegar ég reyni að starta virtual vélinni

**Comment by IronPeak** [comment]
Hefuru aðgang að því að gera eitthvað í virtual vélinni?

**Comment by Kristoferu16** [comment]
Ekki meir en bara settings flipinn efst í virtual box glugganum er bara fastur á þessari skjámynd

**Comment by IronPeak** [comment]
Ok, held að eina leiðinn sé að setja upp nýja :/

**Comment by Kristoferu16** [comment]
jæja það verður fjör á mrg :(
