### ISSUE TITLE
Misræmi í 2015 spurningu og glærum í ár - hvort er rétt?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#115]
"Deployment should use the same process for every environment except one - which one?"

En þetta stendur á glærunum? Eins og maður eigi undantekningarlaust alltaf að nota sama deployment process í hvaðeina umhveri sem maður deploy-ar í.
![screen shot 2018-12-13 at 13 36 43](https://user-images.githubusercontent.com/16048954/49942133-5fe67880-fedc-11e8-86d4-ce98af6f330c.png)

Nú er ég alveg rugluð - hvaða environment er undantekning, veit það einhver?

**Comment by hermanno16** [comment]
Er nokkuð verið að tala um dev-dependencies? Maður vill náttúrulega ekki deploya testunum og jest á prod

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49944053-61ff0600-fee1-11e8-9111-621fa509d049.png)
Þetta er beint úr glærunum líka

**Comment by eddast** [comment]
Ok mjög ruglandi :/ takk!
