### ISSUE TITLE
Varðandi verkefni vikunnar og fyrirlestraglærur

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#12]
Sælir,

Getum við áætlað að verkefni vikunnar eða a.m.k. verkefni morgundagsins inn í dag?

Líka, mætti ég benda á að það væri gagnlegt ef að glærur kæmu tímanlega inn fyrir fyrirlestrana t.d. kvöldið áður svo hægt væri að átta sig betur á áherslum og efni þar sem það er oft öðruvísi en í bókinni :)

**Comment by stefaneg** [comment]
Erum alltaf að reyna að koma þessu tímanlega inn, tekst sjaldnar en við vildum.
