### ISSUE TITLE
upptökupróf_2015 - Q.8

### ISSUE THREAD

**Issue by vidir17** [hgop/syllabus-2018#121]
**8.	What is the difference between continuous delivery and continuous deployment pipelines?**

Mér finnst erfitt að skilja muninn á síðasta skrefinu í þessum pipelines. Er þá continuous delivery automatic og tilbúið sem er sent strax á netið sem "update" á hugbúnaði?
Continuous deployment er þá eins nema farið í exploratory og usability testing áður en útgáfan er gefin út? Er ég að skilja þetta rétt?

**Comment by skulia15** [comment]
Eins ferli með continuous delivery þarf manual deployment á meðan continuous deployment er released um leið og öll próf standast

**Comment by eythoro16** [comment]
ég hugsa það allavega þannig. **Continuous delivery has a manual stage of deploy to production. Continuous Automates this stage.**
