### ISSUE TITLE
Vantar folder structure undir game-client

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#128]
Það vantar game-client folderið í skilastrúktur fyrir week 3, lítur út svona fyrir neðan. Gætuð þið bætt við öllum þeim fileum sem á að skila svo ég geti verið alveg viss með afurðina mína :) Takk takk.
```bash
├── game-client
│   ├── Dockerfile
│   └── *
```

**Comment by IronPeak** [comment]
bæti því við
