### ISSUE TITLE
Á að setja Jenkins og Java upp í verify_environment.sh?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#13]
Hæ, þar sem við settum Jenkins og Java bara upp í instance-inu en ekki í environmentinu okkar, þurfum við nokkuð að bæta því við í verify_environment.sh skriftuna okkar?

**Comment by IronPeak** [comment]
Nei, scriptið var hugsað til þess að verify-a development machines svo hlutir sem við notum bara til að keyra Jenkins ættu ekki að vera
