### ISSUE TITLE
Datadog set count to 0

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#130]
Við búum til count metric með `dog.increment('metric-name');`

Er hægt að búa til count metric án þess að gera þetta. 

Sem sagt mig langar að gera count metric fyrir þegar database error gerist þá hækkar count. `dog.increment('Database.failure')`
Nema þar sem Database.failure hefur aldrei gerst þá get ég ekki bætt við bord-ið töflu sem horfir á það count þar sem það er ekki til.

eina leiði sem ég sé hvernig ég get gert þetta er að hafa í byrja á kóðanum

```
dog.increment('Database.failure') 
dog.decrement('Database.failure')
```
ef mér finnst þetta vera hacky way og það hlýtur að vera til betri leið

**Comment by IronPeak** [comment]
mjög líklega til leið, en ég kann hana ekki :)

**Comment by eythoro16** [comment]
væri litið ílla á mig ef ég myndi nota hacky leiðina ❔
