### ISSUE TITLE
Villa í unit tests í week2day2

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#14]
Hæ ég vil benda á að það er villa í gefnu intialization unit testunum í week2day2:

`expect(game.deck.length).toEqual(50);`
á að vera
`expect(game.state.deck.length).toEqual(50);`
og
`expect(game.cards.length).toEqual(2);`
á að vera
`expect(game.state.cards.length).toEqual(2);`

Það semsagt vantar að nesta þennan state property undir game til að testin passi :)

**Comment by IronPeak** [comment]
Velgert 🥇 , lagaði þetta fyrir day 7
