### ISSUE TITLE
Vitlaust unit test gefið í day7

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#15]
Í testinu "guess21OrUnder should draw the next card" sem er gefið í lýsingu í day7 eru þrjú cards dregin frá deckinu
`deck = [ '10H', '09S', '01D', '05L' ];` 
það þýðir að eftirfarandi assert:
`expect(game.state.cards[2]).toEqual('01D');`
er vitlaust, þar sem fyrsta drawið er 05L, annað drawið er 01D og þá auðvitað á þriðja drawið sem er  game.state.cards[2] að vera 09S, ekki 01D :)

**Comment by IronPeak** [comment]
klúður :D
komið inn fix
