### ISSUE TITLE
Afhverju eru tvö spil dregin í byrjun í Lucky21 initial state? Á ekki bara að vera eitt?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#17]
Á ekki bara að vera eitt sem er dregið í byrjun og SVO giskar user og þá er dregið annað?
Ég spyr því að það virðist m.v. testið "guess21OrUnder should draw the next card", því það indicatear að þegar notandi GISKAR er dregið nýtt úr deckinu - þá ætti initial stateið ekki búið að vera að draga meir en eitt spil  -- annars hvað á maður að gera ef maður fær tvö spil t.d. 13+13, þau eru auðvitað alltaf yfir 21?

**Comment by IronPeak** [comment]
Mannspilin eru öll 10 stig á meðan ásin er annað hvort 1 eða 11 stig eftir því hvort er betra fyrir playerinn.
Svo þú getur aldrei tapað með bara 2 spilum.

**Comment by eddast** [comment]
OK, virðist ekki vera þannig logík í appinu -- ertu einhverstaðar með yfirlit eða reference fyrir utan appið fyrir leikreglur þessa leiks?

**Comment by IronPeak** [comment]
svoldið misvísandi þegar unit testið fyrir þetta var vitlaust eins og þú bentir á í #15

**Comment by eddast** [comment]
OK, það er allt önnur lógík í appinu -- þar er dregið eitt spil í byrjun og mannspilin virðast corresponda við tölur sínar. Plús þar kemur hvergi fram þetta edge case með ásinn. Ertu einhverstaðar með yfirlit eða reference fyrir utan appið fyrir leikreglur þessa leiks? Eru fleiri "edge cases" sem þarf að vita af?

**Comment by IronPeak** [comment]
Held þetta sé allt, en skal setja section inní dag 7 eftir vinnu :)

**Comment by IronPeak** [comment]
Komin inn lýsing á reglunum.
