### ISSUE TITLE
Day 6 - Part 6 - id_rsa

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#18]
sudo cat /var/lib/jenkins/.ssh/id_rsa
fatta þetta nú ekki, það eina sem .ssh folder-inn í instance-inu inniheldur er knowshosts file. er eitthvað skref sem ég missti af þar sem við eigum að generate-a id_rsa fyrir jenkins?

**Comment by eythoro16** [comment]
fæ nátturulega bara permission denied(publickey) af því að þessi rsa key er ekki til.

**Comment by IronPeak** [comment]
ættuð að búa til nýjan SSH key fyrir Jenkins userinn til að tengjast við GitHub.
bætti við dag 6 svo það sé skýrara :)
