### ISSUE TITLE
Concurrent vandamál með docker compose fyrir postgres og api containerinn

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#2]
Hæ,
Er að fá villu þegar ég er að reyna að keyra upp Postgres containerinn og API containerinn á sama tíma með Docker compose. API-inn nær ekki að tengjast við postgres container-inn með kóðanum óbreyttum. Eina sem ég hef breytt er að endurskýra database-inn í nafnið sem ég skýrði í docker-compose. (Ég er btw búin að fullvissa mig um að öll env gildi koma rétt inn í client breytuna í database.js).

Ef ég console-logga errorinn sem kemur er hann harla descriptive og kemur hann svona:

![image](https://user-images.githubusercontent.com/16048954/49078210-4f27d880-f235-11e8-9248-8edd54873ecd.png)

En fáranlega er að ef ég reyni svo að logga client-inn þá STUNDUM ná báðir að að keyra upp og allt virkar 100%, þannig mér dettur helst í hug að þetta sé concurrent/async vandamál. Er búin að reyna að gera skriftur til að láta Postgres connectionið bíða þar til APIið kemur upp en gengur mjög brösuglega. Er einhver búinn að lenda í þessu og getur leiðbeint mér?

**Comment by eddast** [comment]
OK edit, þetta virkar eftir að ég setti setTimeout function utanum client.connect í database.js:
`setTimeout(() => client.connect((err) => {
/* snipped */
}), 2000);`

En er ekki til betra workaround eða eitthvað sem ég get gert í þessu?? :(

**Comment by IronPeak** [comment]
Flott @eddast , bætti þessu workaround við fyrir daginn.
