### ISSUE TITLE
isGameOver fallið

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#20]
er isGameOver fallið bara fyrir þegar user tapar (game over in the sense að hann tapaði leiknum) eða líka er það skilgreint líka sem true í isGameOver þegar hann playerinn vinnur s.s. einhver niðurstaða komin í leikinn?

**Comment by IronPeak** [comment]
playerWon segir til um hvort hann hafi tapað
gameOver er hvort leikur inn sé ongoing
