### ISSUE TITLE
ssh hangir í week2day1

### ISSUE THREAD

**Issue by gudberg** [hgop/syllabus-2018#22]
Hæhæ,

skipunin til að ssh-a sig inn í instanceið hangir þegar ég nota JenkinsAWSKeyPair.pem og kemur svo time out. Þarf ég að endurnýja eitthvað credentials?

**Comment by IronPeak** [comment]
Nei ætti að virka áfram til að tengja sig inní instancið, passaðu að instanceið sé reachable á port 22 frá þinni IP tölu.

**Comment by gudberg** [comment]
ahh alveg rétt, IP talan er vandamálið. Takk fyrir
