### ISSUE TITLE
Hvað er lesefni/fyrirlestrarefni morgundaginsins og fimmtudags?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#24]
Fyrst Automatic Acceptance Testing var tekið fyrir í dag en stóð til að taka á morgun skv. syllabus, hvert er lesefni/fyrirlestrarefni morgundagins? En á fimmtudag?

**Comment by stefaneg** [comment]
Var að uppfæra dagskrá vikunnar. Ekkert lesefni fyrir fimmtudag, stuttur fyrirlestur á morgun.
