### ISSUE TITLE
Ef player giskar Over21

### ISSUE THREAD

**Issue by evasif** [hgop/syllabus-2018#25]
Ef að player giskar Over21 og fær einmitt 21 er hann þá ekki búin að tapa? 
Er það ekki rétt skilið?

**Comment by IronPeak** [comment]
já hann myndi tapa :)

**Comment by IronPeak** [comment]
ættla að reyna að búa til betri útskýringar á leikreglunum í kvöld.

**Comment by IronPeak** [comment]
kominn inn (vonandi) betri útskýring á leiknum :)
