### ISSUE TITLE
Jenkins webhook og branches

### ISSUE THREAD

**Issue by Skandalabrandur** [hgop/syllabus-2018#28]
## Er einhver leið til að fá webhook notifications til þess að virka fyrir branches?

Prófaði að búa til branch sem hét "thorsteinn_docker_repo" og pushaði breytingum þar inn eftir að hafa sagt Jenkins að nota þetta branch með "*/thorsteinn_docker_repo".

Virkaði svo að build-a með "Build now".

Undir "Manage Jenkins > System Log" var auðveldlega hægt að sjá að Jenkins var að fá webhook post request á <JENKINS-INSTANCE>/github-webhook/ þegar ég pushaði svo enn einum breytingunum þar inn

En í project undir "GitHub Hook Log" var ekkert að finna.

Um leið og ég eyddi branchinu og stillti Jenkins projectið aftur á master þá virkaði allt eins og smurt.

Hefur einhverjum tekist að nota branches?

**Comment by IronPeak** [comment]
https://stackoverflow.com/questions/15344955/hudson-jenkins-git-build-all-branches

**Comment by Skandalabrandur** [comment]
Breytti branch specifier í ** en það virðist ekki virka.
Lausnin okkar er þó bara að nota sama Jenkins instance báðir með því að búa til annan notandaaðgang
