### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by Danielev8** [hgop/syllabus-2018#30]
What are the ESLint options are we looking for, should we be looking to fix "prefer-const" and other strict things like that?
+ Do we need to set the ecmaVersion to 6? Otherwise it check for errors that should not be there.

**Comment by IronPeak** [comment]
An oversight on my part, added:
It should create a .eslintrc.json, add es6 to the configuration:

{
    "extends": "google",
    "env": {
        "es6": true
    }
}

You can modify the settings however you want, but the should enforce a consistent coding standard.
