### ISSUE TITLE
Terraform: SSH handshake failed

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#32]
Hæhæ, er á að reyna að gera deployment partinn af í week2day3 verkefninu en fæ ALLTAF eftirfarandi villu eftir að terraform er búið að keyra í c.a. 5-6 mínútur að reyna að búa til instance:

```
.....
[0m[1maws_instance.game_server: Still creating... (5m30s elapsed)[0m[0m
[31m
[1m[31mError: [0m[0m[1mError applying plan:

1 error(s) occurred:

* aws_instance.game_server: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
```

Er alveg að vera vitlaus á þessu, það tekur svo langan tíma að keyra og fá villu þannig debugging er helvíti.

Google segir að þetta séu access réttindi vesen fyrir GameKeyPair.pem fyrir Jenkins notandann en er búin að reyna allt til að gefa honum rétt réttindi að GameKeyPair.pem í instanceinu - er búin að reyna að runna sudo chown -R jenkins . inní ~/.aws/ sem Jenkins, er búin að reyna að breyta infrastructure.tf og bæta við connection { ... agent = false } gildi virkaði ekki,  og ég búin að runna chmod 400 og chmod 600 og jafnvel chmod 644 á GameKeyPair.pem  sem Jenkins í instancinu og gera well bara allt annað sem mér dettur í hug en ekkert virkar.

Kannast einhver við þetta og hefur ráð? Er orðin mjög MJÖG desperate.

**Comment by IronPeak** [comment]
ef þú loggar þig inn á jenkins userinn, geturu gert:
`cat ~/.aws/GameKeyPair.pem`

**Comment by eddast** [comment]
Já, án sudo ekkert mál

**Comment by eddast** [comment]
Gæti verið að einhverju þurfi að breyta í infrastructure.tf filenum til að Jenkins geti notað Terraform eða á hún að vera nákvæmlega eins og í week1day4?

**Comment by eddast** [comment]
Update: búin að prófa að breyta user í infrastructrue.tf í jenkins og í ec2-user eins og einhver suggestaði á netinu, án árangurs. Alveg að missa vitið :)))))))

**Comment by eddast** [comment]
Já, 100% sá sami og ég er með locally

**Comment by IronPeak** [comment]
Það sem þarf að vera til staðar hjá jenkins userinum:
~/.aws/credentials - þarf að innihalda aws educate sessionið
~/.aws/GameKeyPair.pem - lykillinn sem AWS generateaði 
/var/lib/jenkins/terraform/hgop/production/docker-compose.yml
/var/lib/jenkins/terraform/hgop/production/infrastructure.tf
/var/lib/jenkins/terraform/hgop/production/scripts/initialize_game_api_instance.sh

**Comment by eddast** [comment]
Credentials er til, er rétt og up-to-date, GameKeyPair er rétt og matchar local key pairið, og allar þær skrár sem eru í /var/lib/jenkins/terraform/hgop/production sem þú tekur fram að ofan eru til staðar. :( :(

**Comment by eddast** [comment]
Það virkar ekki.
Hinsvegar þá er terraform að ná að búa til instance-ið af GameServer. Honum tekst ekki að færa initialize_game_api.sh yfir á nýja instance-ið. Þegar ég reyni svo að ssh-a mig inná instance-ið manually með ssh loggum þá kemur það svona:
```

debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: GameKeyPair.pem
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
ubuntu@ec2-34-229-242-56.compute-1.amazonaws.com: Permission denied (publickey).
```

Er búinn að kanna GameSecurityGroup og það leyfir ssh:
![image](https://user-images.githubusercontent.com/16048954/49529029-162eda00-f8ad-11e8-8edb-6748cf669e5f.png)

**Comment by IronPeak** [comment]
could you create a temporary password for your aws educate account and send me the credentials + the GameKeyPair.pem file?
HrafnOrri1207@gmail.com

**Comment by eddast** [comment]
Takk -- þú ert með email!
