### ISSUE TITLE
jenkins pipeline villa day8-part4

### ISSUE THREAD

**Issue by helgaeythors** [hgop/syllabus-2018#33]
Í Jenkinsfile erum við að reyna keyra eslint og unit testin með yarn en jenkins pipeline buildið stoppar á því, fáum villuna "error Couldn't find a package.json file in "/var/lib/jenkins/workspace/hgop pipeline"
Við erum með package.json í hgop pipeline/game-api, ætti game-api mappan að vera workspace-ið fyrir jenkins?
Virkar heldur ekki að setja afrit af package.json í rótina.

**Comment by Danielev8** [comment]
add this to the end of the end of npm run test:unit
```
npm install --prefix game-api
``` 
should work

**Comment by IronPeak** [comment]
getið notað
```
    dir("some directory") {
        sh "some command to run inside the directory"
    }
```
eða
sh "cd game-api && npm install"
