### ISSUE TITLE
Villa í week2day4 í app.js og dealer.unit-test.js

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#35]
Hæhæ, vil benda á að kóðinn sem er gefinn fyrir app.js í week2day4 er gallaður
```
const context = require('./context.js').newContext();
const server = context('server');
server.listen();
```
server breytan er nefnilega fall sem þarf að taka inn context annars fúnkerar það ekki, þannig það væri t.d. hægt að gera

```
const context = require('./context.js').newContext();
const server = context('server')(context);
server.listen();
```

Þ.a. að context parameterinn er settur inn í server, þá virkar þetta. Annars er auðvitað villa því server.js fær ekki context frameworkið. :)

Líka þá á þetta fall í dealer.unit-test.js:
```
function newRandom(randomReturnValues) {
    let i = 0;
    return {
        random: (min, max) => {
            return randomReturnValues[i++];
        }
    };
}
```

Ekki að skila objecti með fallinu random heldur randomInt, svona:

```
function newRandom(randomReturnValues) {
    let i = 0;
    return {
        randomInt: (min, max) => {
            return randomReturnValues[i++];
        }
    };
}
```

As per það sem er sett í random.js :)

**Comment by IronPeak** [comment]
Velgert :D
Setti kóða breytingarnar þínar inn
