### ISSUE TITLE
Nokkur 'typos' í gefnum server.js kóða í week2day4

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#39]
Hæhæ, vil benda á nokkrar typos í server.js skránni sem er gefin til að fólk þurfi ekki að debugga.

`const database = context("database");`
 þarf að breyta í
```
const databaseConstructor = context("database");
const database = databaseConstructor(context);
```
til að fúnkera því það tekur inn contextið

`app.post('guess21OrUnder', (req, res) => {`

þarf að breyta í

`app.post('/guess21OrUnder', (req, res) => {`

og að sama skapi þarf að breyta

`app.post('guessOver21', (req, res) => {`

í

`app.post('/guessOver21', (req, res) => {`

og að lokum  þarf að breyta

`res.send(lucky21.getState(game));`

í

` res.send(game.getState(game));`

þá ææææætti þetta að vera á góðri leið :)

**Comment by IronPeak** [comment]
Velgert, setti þetta inn :)
