### ISSUE TITLE
python: can't open file 'app.py':[Errno 2] no such file or directory

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#4]
Er í part 3

![image](https://user-images.githubusercontent.com/24224443/49104354-a2ba1680-f275-11e8-8f78-dee9376e5efb.png)

þegar ég nota compose-up fæ ég allaf þetta up. er ég að miskilja leiðbeininganar?

docker-compose.yml
![image](https://user-images.githubusercontent.com/24224443/49104901-1ad50c00-f277-11e8-9ae5-87edb9f5e72b.png)

database.js getClient
![image](https://user-images.githubusercontent.com/24224443/49104917-27596480-f277-11e8-9834-5f2924992437.png)

þetta á bara að vera svona right? 

ps: sorry að þetta sé myndir, fæ 'insert code' ekki til að sýna kóðan nema í einni línu

**Comment by IronPeak** [comment]
Þarft að uppfæra docker-compose.yml skránna til þess að nota imageið þitt á docker hub í staðinn fyrir "username/repo:tag".

**Comment by eythoro16** [comment]
Never mind. gleymdi að taga image-ið aftur(var að gera þetta allt aftur í annari vél) áður en ég pushaði.

Og nuna virkar þetta.
Stupid me
