### ISSUE TITLE
git clean.

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#42]
Ég er smá confused hvar ég á að runna git clean. Hvert er repository-ið clone-að í jenkins?

**Comment by eythoro16** [comment]
er það rétt hjá mér að það á að runna 'git clean ' í /var/lib/jenkins/test/<repositoryName>/  ?

**Comment by IronPeak** [comment]
Jenkins býr til workspace fyrir jobið þitt og svo eru þið að pulla repositoryið inní það workspace.
En Jenkins cleanar repoið ekki á mill svo þið þurfið að gera það sjálf svo build filear séu ekki að hafa áhrif á seinni builds.

**Comment by eythoro16** [comment]
þá /var/lib/jenkins/workspace/<pipeline-name>?

**Comment by eythoro16** [comment]
ætla að giska að það sé folderinn. Follow up spurning með clean step í jenkins. kemur commit stage-ið ekki annars á eftir build stageið? Og build stage-ið ætti enþá að innihalda docker buid og docker push
