### ISSUE TITLE
NPM/Docker build hangs forever

### ISSUE THREAD

**Issue by IronPeak** [hgop/syllabus-2018#43]
Update your `game-api/Dockerfile`:\
From:\
`RUN npm install`\
To:\
`RUN npm install --production`

**Comment by Kristoferu16** [comment]
Er búinn að bæta við production og  upgradea aws vélina úr t2.micro í t2.small samt er þetta að hanga bara á annaðhvort npm install eða terraform destroy í ca annaðhvert skiptið. Það er eiginlega bara ómögulegt að vinna í þessu því ég er að reboota serverinn á svona korters fresti einhverjar hugmyndir?

**Comment by Kristoferu16** [comment]
mér sýnist þetta vera að virka allavega fljótt á litið takk fyrir þetta er búið að vera að gera mig brjálaðann
