### ISSUE TITLE
day08-setup

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#45]
er það eðilegt að það taki jenkins 6 mins að runna npm install?

**Comment by IronPeak** [comment]
Gæti þetta verið vandamálið:
https://github.com/hgop/syllabus-2018/issues/43

**Comment by eythoro16** [comment]
ég prófaði þetta en það tekur samt 7 mínótur að runna npm install

**Comment by eythoro16** [comment]
```
node {
  def git = checkout scm
    stage("Build") {
      sh "./scripts/docker_build.sh ${git.GIT_COMMIT}"
      sh "./scripts/docker_push.sh ${git.GIT_COMMIT}"
    }
    stage("Commit") {
      // Clean
      sh "cd game-api && git clean -dfxq"
      sh "cd game-api && git stash"
      // [Setup](url)
      sh "cd game-api && npm install"
      // Lint
      sh "cd game-api && npm run eslint"
      // Test
      sh "cd game-api && npm run test:unit"
    }
    stage("Deploy") {
      
    }
}
```svona er jenkinsfile-inn

**Comment by eythoro16** [comment]
svo sýnist mér að hann er lengri og lengri að build eftir hvert build. setup er komið up í 11 mins og 37 sec

**Comment by Kristoferu16** [comment]
Ég er að lenda í því að buildið stoppi bara alvega á setup steppinu og þá get ég ekkert gert þangað til að buildið timear out eða eitthvað sýndi @IronPeak  þetta áðan og þá virkaði að bæta við #43 en þetta er byrjað að gerast aftur

**Comment by Kristoferu16** [comment]
er núna t.d. alveg locked out frá jenkins og get ekkert gert hvorki ssh né accessað það í browser

**Comment by IronPeak** [comment]
Tók aldrei svona langan tíma þegar ég var að þessu.
Gætuð prófað að nota yarn og séð hvort það keyri hraðara fyrir ykkur.
Annars get ég litið á þetta í dæmatíma á morgun.

**Comment by eythoro16** [comment]
þetta lagaðist hjá mér. ég þurfti bara a reboot-a instance-ið

**Comment by eythoro16** [comment]
besta fix-ið við öll tölvuvandamál. instance var líka að biðja um það þegar ég ssh inná það
