### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by unnurhalldors** [hgop/syllabus-2018#46]
Hæhæ,

Við erum að vinna í Deployment Job og fáum eftirfarandi villu þegar við reynum að copy-a .tf skrár úr repository í /var/lib/jenkins/terraform/hgop/production.

**cp: cannot create regular file '/var/lib/jenkins/terraform/hgop/production/infrastructure.tf': Permission denied**

Jenkins notandinn er með SSH lykil til þess að hafa aðgang að github repository-inu okkar. Hvað gæti vandamálið verið hér? Takk!

**Comment by IronPeak** [comment]
gæti verið að þið hafið búið production folderinn á ubuntu userinum.
þá á "ubuntu" userinn directoryið og jenkins hefur ekki aðgang að því.
getið prófað að delete-a directoryinu og búa það til aftur á jenkins usernum.

**Comment by unnurhalldors** [comment]
Já það passar! En þegar ég reyni að búa til möppuna á jenkins usernum þarf ég að setja inn "[sudo] password for jenkins:". Settum við einhverntíman password fyrir jenkins userinn? :)

**Comment by IronPeak** [comment]
ættir aldrei að nota sudo á jenkins usernum
þarft líklega að delete öllum möppunum terraform/hgop/production og búa þær til aftur
en svo gætiru líka gefið jenkins aðgang að möppunni með chmod (þarf að runna því á ubuntu usernum)
en líklega einfaldast að recreate-a þær bara.

**Comment by unnurhalldors** [comment]
Takk kærlega!
