### ISSUE TITLE
Að setja public IP fyrir API instancið í readme

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#49]
Núna alltaf þegar við pushum á master á HGOP repositoryinu verður til nýtt GameAPI instance og því fyrra sem var til eytt með nýrri public IP. En í verkefnalýsingu fyrir week2 eigum við að setja í README.md hvaða URLi GameAPI instancið okkar keyrir á -- hvernig viljiði að við gerum það þ.e. skrifum í readme hvaða public IP og url er currently uppi fyrir GameAPI-inn okkar þegar það verður bara til nýtt instance með nýrri public IP þegar við skirfum í READMEið? Eigum við bara að vera geggjað fljót að stöðva pipeline-ið þegar við skrifum í README-ið eða?

**Comment by IronPeak** [comment]
hugsaði ekki fyrir því, uppfærði dag 10.
