### ISSUE TITLE
Day3 Lab Skilaafurð

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#5]
Hæ, ég sé að það er engin skilaafurð sem maður skilar frá sér í AWS labinu í dag (nema viðbótinni á verify_environment.sh skriftunni). Þýðir það að það þurfi að mæta í dæmatíma til að sýna fram á að maður hafi unnið labið eða er þetta bara æfing sem nægir að ljúka þó engin eiginleg skilaafurð fáist til að sýna fram á það?

**Comment by IvarKristinn** [comment]
Er það ekki bara að gera ferlið og bæta í scriptuna ?

**Comment by eddast** [comment]
Það er einmitt spurningin mín, hvort það nægi eða hvort þurfi að sýna fram á það í tíma að maður hafi gert ferlið :)

**Comment by IronPeak** [comment]
Við förum yfir alla vikuna í einu. Ætti ekki að vera mikið af skilaafuruðum úr degi 3, en hann er mest hugsaður sem undirbúningur fyrir dag 4.
