### ISSUE TITLE
Duplicate security group

### ISSUE THREAD

**Issue by hkh95** [hgop/syllabus-2018#50]
Hæhæ erum að fá einhvern error á security group -->

* aws_security_group.game_security_group: Error creating Security Group: InvalidGroup.Duplicate: The security group 'GameSecurityGroup' already exists for VPC 'vpc-9541efef'

Er ekki búinn að finna neitt á google sem segir mér hvað er að en það er eins og hann sé að reyna að búa hann til tvisvar.. eruði með einhver ráð við þessu ??

Þetta gerist í excecute shell scriptunni nánar tiltekið terraform apply

**Comment by devalberg** [comment]
Deleting the security group in aws console fixed this for us :D

**Comment by eythoro16** [comment]
i´ll second that

**Comment by hkh95** [comment]
ah okei næs takk !
