### ISSUE TITLE
da09 - testing - Now do this for the other files.

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#54]
hvaða file eru þá að vera að tala um? bara lucky21.unit-test.js?

**Comment by eythoro16** [comment]
þarf deck.js að hafa context?

**Comment by eythoro16** [comment]
ég er svo villtur með hvernig á að breyta fallinu

**Comment by eythoro16** [comment]
ég skil líka ekki hvernig á að breyta deck.js til að nota context

**Comment by IronPeak** [comment]
beyta project fileunum svo þeir nota context til þess að sækja dependencies í stað þess að (fá þær inn sem parameter eða nota require)

```javascript
const inject = require("./inject.js");

test('guess21OrUnder should draw the next card', () => {
  // Arrange
  let deck = deckConstructor();
  deck = ['10H', '09S', '01D', '05C'];
  let dealer = dealerConstructor();
  // Override the shuffle to do nothing.
  dealer.shuffle = deck => {};

  // Inject our dependencies
  let game = lucky21Constructor(inject({
    dealer: () => dealer,
    deck: () => deck,
  }));

  // Act
  game.guess21OrUnder(game);

  // Assert
  expect(game.state.cards.length).toEqual(3);
  expect(game.state.cards[2]).toEqual('09S');
});
```

**Comment by eythoro16** [comment]
```
module.exports = context => {
  let random = context('random');
  return {
    shuffle: deck => {
      for (let i = 0; i < deck.length - 1; i++) {
        const j = random.randomInt(i, deck.length);
        const card = deck[j];
        const old = deck[i];
        deck[i] = card;
        deck[j] = old;
      }
    },
    draw: deck => {
      const card = deck.pop();
      return card;
    }
  };
};
```
dealer.js á ekki að vera svona right?

**Comment by eythoro16** [comment]
https://github.com/hgop/syllabus-2018/issues/54#issuecomment-445282788 er semsagt ekki fullklárað right?

**Comment by eythoro16** [comment]
þá að gera eins og þetta sem var gefið okkur Part 3 - Test Doubles?

**Comment by eythoro16** [comment]
það sem er líka að confuse-a mig er að þegar 
```
const randomConstructor = context('random');
const random = randomConstructor(context);
```
er set þá hættir 
`test('dealer should should shuffle cards', () => {...`
að virka og gefur mér að randomConstructor sé ekki function

**Comment by eythoro16** [comment]
> T.d. unit testið sem hérna að ofan þyrfti að bæta við að injecta random í dealerConstructorinn eftir að þú bætir við random.js.

en ætti af hverju ætti að þurfa an injecta random í dealerConstructorinn þegar ég vill ekkert breytta random.

**Comment by IronPeak** [comment]
context('random') ætti að returna function miðað við kóðan úr dag09.

því dealer dependar á að fá random in, ef dealer constructorinn reynir að sækja random úr contexinu án þess að það sé inni kemur villa.

**Comment by eythoro16** [comment]
mmmh. bætti við 
```
let dealer = dealerConstructor(
    inject({
      random: () => {}
    })
  );
```
fæ pass. En þá virkar ekki gefin kóðinn fyrir dealer.unit-test

**Comment by eythoro16** [comment]
af hverju nóta dealer.unit-test 
```
let newDealer = require('./dealer.js');
  let dealer = newDealer(name => {
    return dependencies[name];
  });
```
í staðinn að nota inject

**Comment by eythoro16** [comment]
sorry, fyrir þennan langa spurningar lista. Svaf yfir mig, þannig að ég gat ekki mætt í dæma tíma.

**Comment by IronPeak** [comment]
```javascript
function newRandom(randomReturnValues) {
    let i = 0;
    return {
        randomInt: (min, max) => {
            return randomReturnValues[i++];
        }
    };
}

test('dealer should should shuffle cards', () => {
    // Arrange
    let dependencies = {
        'random': () => newRandom([2, 1]),
    };
    let newDealer = require('./dealer.js');
    let dealer = newDealer((name) => {
        return dependencies[name];
    });
    let deck = ['a', 'b', 'c'];

    // Act
    dealer.shuffle(deck);

    // Assert
    expect(deck).toEqual(['c', 'b', 'a']);
});
```

Bara önnur leið til að gera það sama, getur notað inject.js sem við gerðum eða búið til þitt eigið function sem returnar dependencies eins og er gert í testinu.

Ekkert mál

**Comment by eythoro16** [comment]
Takk fyrir hjálpina
