### ISSUE TITLE
The Jenkins deploy job should output the ip the game API is running on to the console.

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#58]
var að sjá þetta núna. Hvernig myndi þetta verið gert?
myndi þetta vera gert í jenkinsfile?
á git pipeline-ið að output þessu í deploy staginu?(sé reyndar ekki fyrir mér hvernig það væri gert)
eða er bara að tala um seinna pipeline-ið ætti að output ip í endanum? Það núþegar gerir það keyrslunni.

**Comment by IronPeak** [comment]
ef við getum séð IPið á APIinu inní jenkins consoluinu fyrir deployment þá er þetta komið.
Ef þetta er enþá inní Jenkins deployment job scriptunni:
`echo "Game API running at " + $(terraform output public_ip)`
þá ættiru að vera nokkuð öruggur.
