### ISSUE TITLE
Jenkins hættur að starta build-a korter í skil..

### ISSUE THREAD

**Issue by laufey92** [hgop/syllabus-2018#59]
Við töldum okkur vera með flest allt komið inn og hann buildaði alla leið fram að deploy þar sem við áttuðum okkur á því að credentials væri útrunnið.  Eftir að hafa restartað því hætti Jenkins  bara öllu buildi, bæði manually og þegar það er pushað frá git.

Eina sem við náum frá outputinu er "Shh: connect to host github port 22: connection timed out".
Er einhver snillingur með lausn? :)

**Comment by evasif** [comment]
Við lentum líka í þessu, ætluðum að builda í síðasta skipti og eina sem við gerðum var að updatea readme og þá bara hætti þetta að virka, skiljum ekkert :( 
Komumst ekki inná Jenkins né getum ssh-að okkur inná vélina, en instance-ið er í gangi inná AWS. 
Fáum sömu villu og fyrir ofan...
Er engin með lausn?

**Comment by evasif** [comment]
Ég kemst allt í einu inná Jenkins núna, skil ekki alveg hvað er í gangi..

**Comment by kthorri** [comment]
Er þetta ennþá vandamál? Gæti verið að Jenkins sé að ofreyna sig? :)

**Comment by kthorri** [comment]
Endilega opnið issueið aftur ef þetta fer að valda ykkur vandræðum aftur.
