### ISSUE TITLE
Fáum við verkefni vikunar um helgina?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#60]
Væri ógeðslega gott að geta þjófstartað smá um helgina í verkefnum, það verður svo mikið stress og fiff að læra undir rosalega lesefna-heavy próf á sama tíma og við erum að böðlast í verkefnum í næstu viku :/

**Comment by kthorri** [comment]
Dagur 1 kemur í fyrramálið.

Þar er stærsta verkefni vikunar.

Dagur 2 og 3 koma svo fyrir dæmatímann á mánudeginum, en þeir ættu að vera töluvert þægilegri en fyrsti dagurinn.

**Comment by IronPeak** [comment]
Það eru líka eitthver todos í `server.js` og `database.js` sem væri hægt að gera núna :)

**Comment by IronPeak** [comment]
gerum okkar besta en líklegt að lausn á viku 2 komi ekki fyrr en seinni partinn á morgun

**Comment by IronPeak** [comment]
https://github.com/hgop/2018-solution/tree/master/week2

Hérna er lausn á viku 2
