### ISSUE TITLE
Database.js villa

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#63]
Í Database.js þá er taflan búin til með heitið GameResult, en svo þegar það er verið að insert-a niðurstöðum þá er insert-að inní History. Skiptir nokkuð máli hvort heitið við notum?

Einnig þá er einn dálkurinn skýrður InsertDate þegar taflan er búin til en InsertedDate þegar það er verið að Insert-a

**Comment by IronPeak** [comment]
Skiptir ekki máli hvort þið notið, en mun nota GameResult og InsertDate uppá sýni dæmi í framhaldinu.
