### ISSUE TITLE
Vantar progress bar í Clover coverage report

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#66]
Það vantar progressið barið í Cover pluginið í Jenkins. Það kemur svona út í Clover í Jenkins.
![image](https://user-images.githubusercontent.com/16048954/49716069-75dd0a80-fc4a-11e8-8c4a-43e674360989.png)
En kemur svona locally, eins og það ætti að gera:
![image](https://user-images.githubusercontent.com/16048954/49717180-11bc4580-fc4e-11e8-978c-3bc1f62462ab.png)
Þetta er apparently algengt vesen með Clover plugin-ið og hefur eitthvað að gera með að JavaScriptið er ekki alveg að fúnkera eins og það á að gera. Skiptir þetta máli upp á einkunn eða? Þarf ég að laga þetta?

**Comment by IronPeak** [comment]
Þetta er í lagi
