### ISSUE TITLE
Eigum við að unit testa sjálf þær skrár sem ekki eru þegar unit testaðar?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#68]
Þær skrár sem við erum ekki enn búin að útbúa unit tests fyrir samkvæmt verkefnalýsingu í game api, þ.e.
```
app.js
context.js
database.js
inject.js
server.js
```
Hafa að sjálfsögðu ekkert dode coverage í þeim coverage reports sem við útbúum með Clover, sem gerir overall code coverage fyrir verkefnið okkar undir viðmiðunarmörkum.

Er ætlast til að við útbúm unit tests fyrir þessar skrár til að rífa upp coverage prósentuna?

**Comment by IronPeak** [comment]
Það er mjög flott að gera það, en það þarf ekki.
`database.js` verður breytt töluvert í dag 12 svo það er gott að bíða með hann ef þið ættlið að gera unit tests fyrir þessa hluti.
