### ISSUE TITLE
Gömul próf

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#70]
Fáum við aðgang að gömlum lokaprófum úr áfanganum til að spreyta okkur á fyrir lokaprófið?

**Comment by Meggyblond** [comment]
Ég vona það innilega!

**Comment by stefaneg** [comment]
Við gerum eitthvað í því já. Stefnan er að prófið verið tilbúið á miðvikudag, setjum með a.m.k. eitt gamalt próf til hliðsjónar.
