### ISSUE TITLE
API Test Job

### ISSUE THREAD

**Issue by evasif** [hgop/syllabus-2018#76]
Erum smá lost með hvað þarf að vera inní schell skriftunni í API Test Job. 

1. Er það rétt skilið að það þarf að clonea sig aftur inná GIT svipað og deployment, og síðan þyrfti að copya package.json og allar skrár sem enda á api-test og það sem þær dependa á eins og til dæmis server.lib-test.js?

2. Væri það líka rétt pæling að gera, eftir að við höfum copyað þær skrár yfir sem við þurfum:
Terraform apply
yarn test:api
Terraform destroy

3. It should run the API tests against the new apitest instance. Skiljum ekki alveg hvað er átt við hérna? Er bara verið að meina að það á að gera yarn test:api þar sem við copyum skrárnar?

**Comment by IronPeak** [comment]
Ættir ekki að þurf að copya test eða package.json skrárnar neitt.

Fyrsti parturinn í shell scriptunni er alveg eins og í deployment, nema þið sendið `apitest` sem parameter í staðinn fyrir `production` í `terraform apply/destroy`.
Þá eru þið með running instance af API-inu á AWS 

Svo fariði inní repository-ið sem þið clone-uðuð í byrjunn og keyrið api testin á móti nýja instance-inu (þ.e. það kallar á apitest instanceið).

Þá ætti prófið að keyra í gegnum einn leik á móti instance-inu.

**Comment by IronPeak** [comment]
Já API_URL environment variablið þarf að á http://TERRAFORM_PUBLIC_IP:3000

**Comment by hkh95** [comment]
okei næs, það er ekki að virka að exporta svona --> export API_URL=http://$(terraform output public_ip):3000, er einhver önnur leið sem að maður á að nota í svona jenkins scriptum, kemur alltaf bara að linkurinn sé http://:3000...

**Comment by IronPeak** [comment]
þarft að passa að þú sért að kalla á terraform inní apitest möppunni svo hún sé með aðgang að state fileunum, sýnist þú vera að kalla á terraform output innan úr repository möppunni.

**Comment by eythoro16** [comment]
er ég að skilja rétt að, eftir terrafrom init, destroy, apply. þá notar maður export api.... commandið. 
svo `cd ~/` er ekki annars repository-ið þar? þarf svo ekki að gera npm install ef það á að runna `npm run test:api`

**Comment by eythoro16** [comment]
og á að nota `-var enviroment=production` ? ætti það kanski að vera `-var enviroment=apitest`
