### ISSUE TITLE
Connection vesen, dagur 11 

### ISSUE THREAD

**Issue by gudberg** [hgop/syllabus-2018#77]
hæhæ, er ekki að ná að tengjast og þegar ég keyri export API_URL=http://localhost:3000 && npm run test:api fæ ég eftirfarandi villu. Einhverjar hugmyndir hvað gæti verið að valda? 

`
  console.log server.lib-test.js:9
    start: 404 - <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title>Error</title>
    </head>
    <body>
    <pre>Cannot POST /start</pre>
    </body>
    </html>
`

**Comment by IronPeak** [comment]
Er þetta enþá issue?

**Comment by gudberg** [comment]
Neibb komið
