### ISSUE TITLE
session token

### ISSUE THREAD

**Issue by hedinnh** [hgop/syllabus-2018#8]
EDIT: nevermind, var of fljótur að spyrja. þetta á ekkert við nottla :)

**Comment by IronPeak** [comment]
Ef okkur finnst við þurfa að prófa deployment scriptnu þá notum við okkar aws aðgang.

**Comment by hedinnh** [comment]
já æi fattaði eftirá að þetta var ekki góð spurning ;p

Takk fyrir svarið
