### ISSUE TITLE
Verður lokaprófið líka á ensku?

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#80]
Væri gott að hafa það bæði á íslensku og ensku samkv. því að fyrirlestrar og lesefni eru á íslensku og ensku í bland :)

**Comment by hedinnh** [comment]
Já ég tek undir það!

**Comment by stefaneg** [comment]
Prófið verður á ensku, og svör þurfa að vera á ensku, þar sem allt skriflegt efni í áfanganum er á ensku. Kennari verður til staðar í prófinu til að aðstoða ef menn eru t.d. með íslenska hugtakið, en ekki það enska.
