### ISSUE TITLE
docker compose locally

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#84]
`export API_URL=http://localhost:3000 && npm run test:api`

í hvaða file á að setja þetta? dockerfile?

**Comment by skulia15** [comment]
Ég setti API_URL parameterinn í docker_compose_up.sh sem er svo nýttur í docker-compose.yml

**Comment by IronPeak** [comment]
If you are doing:
Try starting your API using docker-compose locally and running your API tests:
`export API_URL=http://localhost:3000 && npm run test:api`

You are supposed to start up your API using docker compose (there is no need to modify anything).
Now that your API is running locally you should execute the command to start the api test.

**Comment by eythoro16** [comment]
en ef ég runna `docker-compose up` þá vill hann nátturulega GIT_COMMIT

**Comment by IronPeak** [comment]
getur notað commit fyrir image jenkins hefur build + pushað en væri líklega snögglegast að gera:
```bash
./scripts/docker_build.sh test
./scripts/docker_compose_up.sh test
```

**Comment by eythoro16** [comment]
og svo þegar ég er búinn að því. runna ég þá `export API_URL=http://localhost:3000 && npm run test:api`?

**Comment by eythoro16** [comment]
yep. takk fyrir hjálpina.
