### ISSUE TITLE
dagur 12 - npm run migratedb:pg && node app.js

### ISSUE THREAD

**Issue by gudberg** [hgop/syllabus-2018#88]
Hann hefur skolast eitthvað til textinn. Þetta er villan sem ég er alltaf að fá þegar ég keyri  npm run migratedb:pg && node app.js skipunina beint í game-api möppunni í fyrrihluta dags 12. Er smá strand hvað gæti verið að valda þessu. Kemur voða lítið gagnlegt úr gúgglinu. 

![screen shot 2018-12-11 at 17 58 39](https://user-images.githubusercontent.com/16470938/49819930-81295680-fd6e-11e8-85b3-26e3220786e7.png)

**Comment by kthorri** [comment]
Getur verið að þú sért að benda á my_database_container en service'in heitir my_postgres_container í docker-compose filenum?

**Comment by IronPeak** [comment]
þarf að keyra þessa command inní docker-compose til þess að hún virki :)

**Comment by Kristoferu16** [comment]
Nei heitir my_database_container á báðum stöðum en er samt með vesen

**Comment by IronPeak** [comment]
hvað kemur út þegar þú runnar þessu inní docker-compose?

**Comment by Kristoferu16** [comment]
![screenshot_7](https://user-images.githubusercontent.com/24221678/49865880-090a7180-fdfe-11e8-9a87-4b8957bd59d2.png)

**Comment by IronPeak** [comment]
þú sentir ekki neinn parameter?

**Comment by IronPeak** [comment]
Prófaðu að keyra:
`./scripts/docker_build.sh mytag && export GIT_COMMIT=mytag && docker-compose down && docker-compose up`

**Comment by IronPeak** [comment]
Þurfið líka að bæta POSTGRES_HOST variable-inu inní docker-compose.yml

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49874183-bdfc5880-fe15-11e8-8869-f642fabb1ae7.png)


fékk þetta

**Comment by IronPeak** [comment]
En ef

**Comment by IronPeak** [comment]
sýnist þið vera með eitthverjar breytingar miðað við það sem er inná GitHub, gætuð þið pushað inn?

**Comment by Kristoferu16** [comment]
heyrðu þetta er komið takk  kærlega :D

**Comment by IronPeak** [comment]
docker-compose yamlið ykkar er hard coded til þess að taka `abc` tag fyrir imageið, þurfið að breyta því.
En til þess að prófa gætuð þið gert:
`./scripts/docker_build.sh abc && export GIT_COMMIT=abc && docker-compose down && docker-compose up`
