### ISSUE TITLE
terraform plan/apply hangs

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#9]
semsagt þegar ég ætlaði að gera terraform apply aftur þá hangir það bara og gerir ekkert.

Ef ég ákveði að gera þetta allt frá byrjun þarf ég þá að delete instancið á aws? þarf ég þá að fara í gegnum meiri hlutan sem var gert í gær, aftur?

**Comment by Hilmar96** [comment]
Þetta gerist vegna þess að credentials tokenið sem þú færð af AWS rennur út eftir klukkutíma (það sem er sett upp í Part 2 af verkefni 4), svo þú þarft að fara aftur á AWS síðuna í Account Details og copy-a  upp á nýtt í ~/.aws/credentials fileinn.

**Comment by eythoro16** [comment]
datt það í hug, Þarf þá að gera terraform init, terraform plan aftur?

**Comment by Hilmar96** [comment]
Það var nóg fyrir mig að copy-a nýjan token inn í fileinn og gera svo terraform apply.

**Comment by eythoro16** [comment]
næs þetta virkaði, takk fyrir hjálpina
