### ISSUE TITLE
Myndirnar eru ekki til staðar þegar keyrt er með docker compose

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#90]
Myndirnar fyrir spilin eru ekki til staðar þegar forritið er keyrt upp með docker-compose up. Vefsíðan er að ná að tala við vefþjónustuna og allt og cards mappan er á sama stað og upprunalega.
Ég hef einnig prófað að færa cards möppuna inní src/ (á sama stað og index.html)

![image](https://user-images.githubusercontent.com/16048954/49822791-02d0b280-fd76-11e8-89e9-12f0da676bfc.png)

**Comment by isabellaf16** [comment]
Þeir breyttu því í dag í json skránni. Ef þú uppfærir repoið frá þeim ætti það að detta inn hjá þér

**Comment by eddast** [comment]
Takk! Fór alveg fram hjá mér!
