### ISSUE TITLE
game-client not copying files on docker

### ISSUE THREAD

**Issue by devalberg** [hgop/syllabus-2018#93]
When building the docker image and running docker-compose up, the cards folder is not being copied at all (not in sources when accessing localhost:4000). The game plays and everything, images are just not present! I have the latest version of the lucky-21-frontend

**Comment by kthorri** [comment]
Hmm, this is when you are running docker-compose locally?

**Comment by devalberg** [comment]
Seems to be happening when I try to build it. Very strange that it SOMETIMES builds and shows images on my partner's computer... but then most of the time it does not.

**Comment by IronPeak** [comment]
Try cleaning docker locally:
`docker system prune`

**Comment by devalberg** [comment]
I tried copying manually cards to dist folder locally and built the image and it worked. So for some reason the npm copy script is not working like it should? No errors are logged while/after copying cards to dist

**Comment by Meggyblond** [comment]
Við erum að lenda í sama

**Comment by IronPeak** [comment]
setjið inn links á repositoryin ykkar (þau þurfa ekki að vera public) og ég skal skoða þetta.

**Comment by devalberg** [comment]
https://github.com/IntelCore2Duo/hgop

**Comment by devalberg** [comment]
Tried adding
```
COPY cards cards
```
In Dockerfile... no difference :/

**Comment by IronPeak** [comment]
what happens when you run ls inside the container?

**Comment by devalberg** [comment]
Ok this is weird... seems to be all there. The only things I have modified are `utils.js` to take it correct ip and right calls, and `server.js` header to allow access.

```
root@35df8cb4fb4d:/code# ls
Dockerfile  README.md  cards  dist  index.js  node_modules  package-lock.json  package.json  src  yarn.lock
root@35df8cb4fb4d:/code# ls dist
10C.svg  2C.svg  3C.svg  4C.svg  5C.svg  6C.svg  7C.svg  8C.svg  9C.svg  AC.svg  App.d36a57b6.css  JD.svg  KD.svg  QD.svg    index.html
10D.svg  2D.svg  3D.svg  4D.svg  5D.svg  6D.svg  7D.svg  8D.svg  9D.svg  AD.svg  App.d36a57b6.js   JH.svg  KH.svg  QH.svg
10H.svg  2H.svg  3H.svg  4H.svg  5H.svg  6H.svg  7H.svg  8H.svg  9H.svg  AH.svg  App.d36a57b6.map  JS.svg  KS.svg  QS.svg
10S.svg  2S.svg  3S.svg  4S.svg  5S.svg  6S.svg  7S.svg  8S.svg  9S.svg  AS.svg  JC.svg            KC.svg  QC.svg  back.svg
root@35df8cb4fb4d:/code#
```

**Comment by GunnlaugurG** [comment]
Ég er að landa í því sama, nema ég var með allar myndir áður en eg lét build processið sjá um að gera image af game-client, þ.e.a.s þegar ég var með harðkóðað image af game-client. En eftir að eg breytti því í að GIT_COMMIT buildi image fyrir mig duttu myndir út.

**Comment by devalberg** [comment]
Starting to wonder if this is reoccurring and not really obvious what is wrong... if we can still get full points for this part if the game runs fine, just doesn't display images. So we can carry on and finish day 13?

**Comment by IronPeak** [comment]
I can't promise full points, but day 13 is not dependent on the UI so you should be able to finish that first :)

**Comment by devalberg** [comment]
Okay, I think I just found the solution... 12 hours later haha :D thanks for your help

**Comment by devalberg** [comment]
They updated the script in day 12 which probably works... But what I did was changed 
```
CMD ["npm", "start"]
```
to 
```
CMD npm run build && npm run start
```
