### ISSUE TITLE
Kafli 11 í bókinni

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#95]
Sælir, kafli 11 í bókinni er sett fyrir sem lesefni en engin fyrirlestur var tekin upp úr því efni -- ég geri ráð fyrir að það sé ekki til prófs eða hvað?

**Comment by hap2000** [comment]
Já þið megið sleppa honum. Það kom stuttlega fyrir í fyrirlestrinum úr kafla 6 sem er tengt efni en þið þurfið ekki að lesa kafla 11.
