### ISSUE TITLE
Game client build klárar ekki á Jenkins

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#96]
Var að bæta við að jenkins build-ar og push-ar game-client í hvert skipti on commit og hann virðist vera fastur alltaf á yarn install (líka npm install) og nær aldrei að klára. Hvað gæti verið að hérna? Er einhver búinn að lenda í sama? Það virkar 100% að build-a locally

**Comment by eddast** [comment]
Virkaði í annað skiptið. Tók samt 10 mínútur að installa. Hvað gæti verið í gangi?

**Comment by eythoro16** [comment]
![image](https://user-images.githubusercontent.com/24224443/49884788-92856800-fe2d-11e8-91c8-84a93e171b77.png)
svona hefur þetta verið 🤷‍♂️

**Comment by devalberg** [comment]
Tried creating another similar build and push script but for UI and called them from the Jenkinsfile, seems to work better. Don't know if we are allowed to do this or not...

Jenkins instance froze when I tried to add the commands after API build commands.

**Comment by IronPeak** [comment]
Getið endur raðað Dockerfiles þannig þeir copy-i files yfir í containerinn eins seint og hægt, þá sérstaklega á eftir  `npm install --production`. Þá nær hann oftast nýta cacheið þegar hann er að builda (þarf ekki að npm installa).
Gott að skoða Dockerfileinn í week 2 solution.
