### ISSUE TITLE
hot-shots villa

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#97]
Er að fá þessa villu þegar ég reyni að initialize-a hotshots client:
![image](https://user-images.githubusercontent.com/16048954/49887259-c9f71300-fe33-11e8-918b-3a0615a1f7f6.png)

Er að nota hot-shots útgáfu 5.9.2

**Comment by IronPeak** [comment]
Sama version og ég, hvernig ertu að calla á StatsD constructorinn?

**Comment by eddast** [comment]
Er með file (hotshots.js) sem lýtur svona út
![image](https://user-images.githubusercontent.com/16048954/49888966-383dd480-fe38-11e8-9c05-5d92380ee141.png)

**Comment by IronPeak** [comment]
þarf meira context, gætiru pushað kóðanum þínum inná eitthvað branch get litið á þetta þar

**Comment by eddast** [comment]
Það er komið inná branch sem heitir hotshots

**Comment by IronPeak** [comment]
prófaðu:
```javascript
return new HotShots({
  host: 'my_datadog_container'
})
```

**Comment by eddast** [comment]
Þetta virkaði!
