### ISSUE TITLE
Request access is denied

### ISSUE THREAD

**Issue by gudberg** [hgop/syllabus-2018#98]
Hæhæ, erum í veseni með docker þannig við þurftum að skipta um repository en nú getum við ekki pushað neinu inná það 

![jenkins](https://user-images.githubusercontent.com/16470938/49888413-daf55380-fe36-11e8-9b77-dd77dc5412bd.png)

**Comment by IronPeak** [comment]
ertu authenticated?

**Comment by Kristoferu16** [comment]
já erum authenticated en man ekki áttum við að vera loggaðir inná ssh jenkins instancinu líka?

**Comment by IronPeak** [comment]
sá sem er að reyna að push imageinu þarf að hafa réttindi til þess.

**Comment by Kristoferu16** [comment]
já erum báðir loggaðir inná sama docker account en þurftum við að configure einhver réttindi fyrir jenkins?

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49891369-42fb6800-fe3e-11e8-80cc-f1de407e88d3.png)
og ég sé images inná jenkins

**Comment by IronPeak** [comment]
já, honum (jenkins) vantar bara aðgang til þess að pusha þeim :)

**Comment by Kristoferu16** [comment]
er það þá aðgangurinn hjá öðrum hvorum okkar eða hvernig geri ég það

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49892101-0cbee800-fe40-11e8-998d-122482d12d0b.png)
þetta kemur þegar eg reyni að logga mig inn

**Comment by IronPeak** [comment]
What version of docker-compose are you using?

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49896268-c7ec7e80-fe4a-11e8-9596-457c48e79e43.png)

**Comment by IronPeak** [comment]
I don't think you need to have docker-compose installed on the jenkins server so you should probably remove it. According to the internet it can sometimes cause issues with docker credential store.

**Comment by Kristoferu16** [comment]
![image](https://user-images.githubusercontent.com/24221678/49903276-8ebe0980-fe5e-11e8-8726-dedab18dfe8d.png)
búinn að removea docker-compose en get samt ekki loggað inn á docker a jenkins

**Comment by IronPeak** [comment]
gætir þurft að restarta.

**Comment by Kristoferu16** [comment]
nope buinn að þvi og ennþá það sama 
![image](https://user-images.githubusercontent.com/24221678/49904037-e2c9ed80-fe60-11e8-9287-beae00861b5a.png)

**Comment by IronPeak** [comment]
Try removing the docker config file:
`rm ~/.docker/config.json`

**Comment by IronPeak** [comment]
prófaðu þá að delete allri `.docker` möppunni

**Comment by IronPeak** [comment]
Ubuntu:
`sudo apt-get remove docker docker-engine docker.io`
`sudo apt autoremove`
`sudo apt update`
`sudo apt upgrade`
`sudo apt-get install docker-ce`
`sudo service jenkins restart`
Jenkins:
`docker login`

Ef þetta virkar ekki, gæti verið fljótlegast að spinna upp nýju jenkins instance og copy allt yfir.

**Comment by Kristoferu16** [comment]
Þetta virkaði ekki spinnumbara upp nýtt jenkins instance á mrg eftir prófið takk fyrir hjálpina :)

**Comment by IronPeak** [comment]
Annars leit ég á verkefnið ykkar, það er smá af ruls fileum inní repositoryinu
`coverage`, `npm-debug.log`
Svo eru þið að collecta coverage á api og capacity tests sem hefur engin áhrif þar sem þið eruð að senda requests á aðra tölvu.
