### ISSUE TITLE
Terraform Apply hangir eftir dag 12.

### ISSUE THREAD

**Issue by jakobj13** [hgop/syllabus-2018#99]
Pipeline-ið var alveg komið hjá okkur, fór í gegnum öll step. Semsagt fór í gegnum öll freestyle-jobbin og endaði með deploy.
Núna stoppar þetta allt í einu á terraform-apply í apa-testinu.

Já ég er með fresh token í credentials, og klullara eftir í session time.

![terraform123](https://user-images.githubusercontent.com/18744495/49889480-899a9380-fe39-11e8-8a96-88ba39e15332.png)

**Comment by IronPeak** [comment]
hvað gerist ef þú reynir að gera thad sama locally?

**Comment by jakobj13** [comment]
Þetta virkaði loksins eftir að ég eyddi öllum instances af GameServer, og öllum security keys. Semsagt full reset á allt inná EC2 management nema Jenkins + glænýr tóken í credentials.
